<?php
/**
 * Dreamrs theme setup.
 *
 * Dreamrs is a block theme: the layout lives in templates/*.html, the design
 * system in theme.json (generated by .dev/build_theme.py), and the sections in
 * patterns/*.php (generated by .dev/build_patterns.py). This file carries only
 * what those cannot express — supports flags, asset enqueues, block styles,
 * pattern categories, and the small filters that keep the theme's forms working
 * inside templates.
 *
 * @package Dreamrs
 */

defined( 'ABSPATH' ) || exit;

define( 'DREAMRS_VERSION', '1.0.0' );

/**
 * Theme supports.
 */
function dreamrs_setup() {
	load_theme_textdomain( 'dreamrs', get_template_directory() . '/languages' );

	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
	add_theme_support( 'editor-styles' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support(
		'custom-logo',
		array(
			'height'      => 48,
			'width'       => 200,
			'flex-height' => true,
			'flex-width'  => true,
		)
	);

	// style.css is loaded into the editor canvas too, so the components below
	// look the same there as on the front end.
	add_editor_style( 'style.css' );
}
add_action( 'after_setup_theme', 'dreamrs_setup' );

/**
 * Front-end styles.
 */
function dreamrs_enqueue_styles() {
	// The theme's own stylesheet by its template path, not get_stylesheet_uri():
	// under a child theme that returns the CHILD's style.css, and every
	// component style in this file would silently stop loading.
	// A child theme enqueues its own stylesheet, as with Twenty Twenty-Five.
	wp_enqueue_style( 'dreamrs-style', get_template_directory_uri() . '/style.css', array(), DREAMRS_VERSION );
}
add_action( 'wp_enqueue_scripts', 'dreamrs_enqueue_styles' );

/**
 * Block style variations.
 *
 * Registered here rather than in theme.json because a style variation needs a
 * label for the editor's Styles panel. Each is a class style.css already
 * carries — never a `style_handle`, which only loads while WordPress serves
 * separate block assets and silently loses its CSS when a plugin turns that
 * off — so a pattern can ask for it by name and an editor can apply it to
 * their own blocks too.
 */
function dreamrs_register_block_styles() {
	$styles = array(
		'core/heading' => array(
			array( 'dreamrs-rule-before', __( 'Title, rule before', 'dreamrs' ) ),
			array( 'dreamrs-rule-after', __( 'Title, rule after', 'dreamrs' ) ),
			array( 'dreamrs-rule-both', __( 'Title, rules both sides', 'dreamrs' ) ),
		),
		'core/group'   => array(
			array( 'dreamrs-tile', __( 'Tile', 'dreamrs' ) ),
			array( 'dreamrs-frame', __( 'Frame', 'dreamrs' ) ),
			array( 'dreamrs-widget', __( 'Widget panel', 'dreamrs' ) ),
		),
		'core/button'  => array(
			array( 'dreamrs-soft', __( 'Soft', 'dreamrs' ) ),
		),
		'core/image'   => array(
			array( 'dreamrs-striped', __( 'Striped backdrop', 'dreamrs' ) ),
		),
		'core/list'    => array(
			array( 'dreamrs-facts', __( 'Facts row', 'dreamrs' ) ),
		),
	);

	foreach ( $styles as $block => $variations ) {
		foreach ( $variations as $variation ) {
			list( $name, $label ) = $variation;
			register_block_style(
				$block,
				array(
					'name'  => $name,
					'label' => $label,
				)
			);
		}
	}
}
add_action( 'init', 'dreamrs_register_block_styles' );

/**
 * Mark the document as scripted before it paints.
 *
 * The project filter chips do nothing without JavaScript, so style.css shows
 * them only under `.dreamrs-js`. Set in the head, not by the deferred script,
 * or the chips would pop in after the page had already laid out.
 */
function dreamrs_js_class() {
	echo "<script>document.documentElement.classList.add('dreamrs-js');</script>\n";
}
add_action( 'wp_head', 'dreamrs_js_class', 0 );

/**
 * The sticky header, scroll reveals, counters, the project filter and the
 * testimonial slider.
 *
 * Deferred and in the footer: everything the script does is an enhancement, so
 * it never needs to hold up rendering. `dreamrs_enable_scroll_animations`
 * switches off the motion — reveals, counting and the slider's autoplay — and
 * leaves behaviour such as the filter and the slider's own buttons alone.
 *
 * The settings go in as JSON, not through wp_localize_script(), which turns
 * `false` into an empty string that the script would read as "on".
 */
function dreamrs_enqueue_interactions() {
	wp_enqueue_script(
		'dreamrs-interactions',
		get_template_directory_uri() . '/assets/js/interactions.js',
		array(),
		DREAMRS_VERSION,
		array(
			'in_footer' => true,
			'strategy'  => 'defer',
		)
	);

	wp_add_inline_script(
		'dreamrs-interactions',
		'window.dreamrsMotion = ' . wp_json_encode(
			array(
				'enabled'  => (bool) apply_filters( 'dreamrs_enable_scroll_animations', true ),
				'previous' => __( 'Previous testimonial', 'dreamrs' ),
				'next'     => __( 'Next testimonial', 'dreamrs' ),
				'slides'   => __( 'Testimonials', 'dreamrs' ),
			)
		) . ';',
		'before'
	);
}
add_action( 'wp_enqueue_scripts', 'dreamrs_enqueue_interactions' );

/**
 * Pattern categories.
 */
function dreamrs_register_pattern_categories() {
	$categories = array(
		'dreamrs-sections' => array(
			'label'       => __( 'Dreamrs: sections', 'dreamrs' ),
			'description' => __( 'Full-width sections for building pages.', 'dreamrs' ),
		),
		'dreamrs-pages'    => array(
			'label'       => __( 'Dreamrs: pages', 'dreamrs' ),
			'description' => __( 'Complete page layouts.', 'dreamrs' ),
		),
	);

	foreach ( $categories as $slug => $args ) {
		register_block_pattern_category( $slug, $args );
	}
}
add_action( 'init', 'dreamrs_register_pattern_categories' );

/**
 * Expand shortcodes inside a Shortcode block wherever it renders.
 *
 * `core/shortcode` only runs wpautop() itself; the expansion normally comes
 * from `do_shortcode` on `the_content`, which never runs for a template part.
 * The newsletter form sits in the footer and the sidebar, so without this the
 * footer would print `[dreamrs_newsletter]` as text. do_shortcode() on output
 * that is already expanded does nothing, so running it everywhere is safe.
 *
 * @param string $content Rendered block.
 * @return string
 */
function dreamrs_render_shortcode_block( $content ) {
	return do_shortcode( $content );
}
add_filter( 'render_block_core/shortcode', 'dreamrs_render_shortcode_block' );

require get_template_directory() . '/inc/front-page-setup.php';
require get_template_directory() . '/inc/contact.php';
require get_template_directory() . '/inc/newsletter.php';
require get_template_directory() . '/inc/shortcodes.php';
require get_template_directory() . '/inc/forms.php';
require get_template_directory() . '/inc/woocommerce.php';
require get_template_directory() . '/inc/scheme.php';
require get_template_directory() . '/inc/updates.php';
